### ISSUE TITLE
Font face not showing

### ISSUE THREAD

**Issue by charge-valtech** [danielhusar/grunt-localscreenshots#2]
Hi there,

Thanks for the great plugin!

I wondered if there was a way to get fonts included with @font-face - At the moment the screenshots seem to fall back to Arial. Not a major deal if not but would be perfect if this was possible.

Cheers

Henry

**Comment by charge-valtech** [comment]
Issue was not including ttf/svg fallbacks. So this is now perfect :-) thanks!!

**Comment by danielhusar** [comment]
Cool :)
